apiVersion: v1
kind: Pod
metadata:
  name: minecraft-pod
  labels:
    app: minecraft
spec:
  containers:
    - name: minecraft-container
      image: openhack/minecraft-server
      ports:
        - containerPort: 25565
      env:
        - name: EULA
          value: "TRUE"