apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-minecraft
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi